apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      deployment: mysql
  template:
    metadata:
      labels:
        deployment: mysql
    spec:
      containers:
      - env:
        image: registry.access.redhat.com/rhscl/mysql-57-rhel7:5.7-47
        name: mysql
