apiVersion: v1
kind: Service
metadata:
  labels:
    app: quotes
  name: quotes
  namespace: secure-secrets
spec:
  ports:
  - name: 8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    deployment: quotes
  type: NodePort
